config/routes.rb
TWAmazon::Application.routes.draw do
  resources :email_notifications
  resources :categories

  match '/landing',    to: 'home#landing'

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :silent_auctions do
    member do
      put 'close'
      post 'confirm_delete'
    end

    collection do
      get 'closed'
      get 'expired'
      get 'future'
      get 'normal_auctions'
      get 'sales'
    end
    resources :auction_messages
    resources :photos, :only => [:index, :create, :destroy]
  end

  resources :bids, :only => [:create, :new, :update] do
    member do
      put 'withdraw'
      post 'update_amount'
      put 'delete'
    end
  end

  resources :faqs, :only  => [:index]

  resources :users, :only => [:show] do
    member do
      get :notification
      get :list_my_items
      get :list_my_normal_auctions
      get :list_my_sales
      get :new_region
      post :update_region
    end
  end

  root :to => 'home#login'
  devise_for :users, :skip => [:sessions], :controllers => { :omniauth_callbacks => "sessions"}
  devise_scope :user do
    get '/login', :to => "sessions#new", :as => :new_user_session
  end

  #Routes to dummy session controller for dev and test environments
  unless Rails.env.production?
    devise_for :users,
      :controllers => { :sessions => "dummy_sessions" },
      :path_names => { :sign_in => '/test_users/login', :sign_out => 'test-users/logout'},
      :except => [:new_user_session, :destroy_user_session]

    devise_scope :user do
      get '/test-users/login', :to => 'dummy_sessions#new', :as => :new_user_session
      get '/test-users/logout', :to => 'dummy_sessions#destroy', :as => :destroy_user_session
    end
  end
end

app/controllers/silent_auctions_controller.rb
class SilentAuctionsController < ApplicationController
  include ApplicationHelper
  include SilentAuctionsHelper

  before_filter :authenticate_user!
  before_filter :ensure_signed_in_user_has_a_region, :only => [:index, :closed, :expired, :future]

  def index
    @title = "Running Silent Auctions"
    @search_category=""
    if params[:search]!=nil
      @search_category=params[:search][:category]
    end
    if @search_category!=""
      @running_auctions = SilentAuction.running_silent_auction(current_user.timezone).recent.includes(:bids).where("region_id = '#{current_user.region_id}' And category_id ='#{params[:search][:category]}'")
    else
      @running_auctions = SilentAuction.running_silent_auction(current_user.timezone).recent.includes(:bids).where("region_id = '#{current_user.region_id}'")
    end
  end

  def normal_auctions
    @title = "Running Auctions"
    @search_category=""
    if params[:search]!=nil
      @search_category=params[:search][:category]
    end
    if @search_category!=""
      @running_auctions = SilentAuction.running_normal_auction(current_user.timezone).recent.includes(:bids).where("region_id = '#{current_user.region_id}' And category_id ='#{params[:search][:category]}'")
    else
      @running_auctions = SilentAuction.running_normal_auction(current_user.timezone).recent.includes(:bids).where("region_id = '#{current_user.region_id}'")
    end
  end

  def sales
    @title = "Quick Sales Board"
    @search_category=""
    if params[:search]!=nil
      @search_category=params[:search][:category]
    end
    if @search_category!=""
      @running_auctions = SilentAuction.running_quick_sales(current_user.timezone).recent.where("region_id = '#{current_user.region_id}' And category_id ='#{params[:search][:category]}'")
    else
      @running_auctions = SilentAuction.running_quick_sales(current_user.timezone).recent.where("region_id = '#{current_user.region_id}'")
    end
  end

  def closed
    @title = "Closed Auctions Listing"
    @closed_auctions = SilentAuction.closed.recent.page(params[:page]).where("region_id = '#{current_user.region_id}'")
  end

  def expired
    @title = "Expired Auctions Listing"
    @expired_auctions = SilentAuction.expired.order("end_date DESC").page(params[:page]).where("region_id = '#{current_user.region_id}'")
  end

  def future
    @title = "Future Auctions Listing"
    @future_auctions = SilentAuction.future(current_user.timezone).recent.page(params[:page]).where("region_id = '#{current_user.region_id}'")
  end

  def new
    @title = "Create new auction"
    @categories = Category.all
    @silent_auction = SilentAuction.new
    @silent_auction.photos.build
  end

  def create
    @categories = Category.all
    @silent_auction = SilentAuction.new(params[:silent_auction])
    @silent_auction.region = current_user.region
    @silent_auction.creator = current_user.username
    respond_to do |format|
      if @silent_auction.save
        flash[:success] = "New item for <b>#{@silent_auction.title}</b> was successfully created!".html_safe

        if params['continue']
          format.html { redirect_to new_silent_auction_path }
        else if params['done']
              if @silent_auction.item_type == 'Silent Auction'
                format.html {redirect_to list_my_items_user_path(current_user)}
              # else
                # format.html {redirect_to list_my_sales_user_path(current_user)}
              else if @silent_auction.item_type == 'Normal Auction'
                format.html {redirect_to list_my_normal_auctions_user_path(current_user)}
              else
                format.html {redirect_to list_my_sales_user_path(current_user)}
              end #end of else if
              end
            end
        end
        unless Rails.application.config.test_mode
          if @silent_auction.start_date.to_date == Time.zone.now.in_time_zone(current_user.timezone).to_date
            UserMailer.send_announcement_to_other_users(@silent_auction).deliver
          else
            UserMailer.send_announcement_to_other_users_now(@silent_auction).deliver
          end
        end
      else
        format.html {
          # to force error message for minimum price has a subject
          @silent_auction.errors[:min_price].each do |msg|
            msg.insert(0, "Minimum price ")
          end
          @title = "Create New Auction"
          @silent_auction.photos.build if @silent_auction.photos.empty?
          render :action => 'new'
        }
      end
    end
  end

  def close
    @silent_auction = SilentAuction.find(params[:id])
    respond_to do |format|
      if @silent_auction.close
        format.html { redirect_to silent_auction_path, :notice => "Auction for <b>#{@silent_auction.title}</b> has been closed".html_safe }
        format.js { render 'close_auction'}
      else
        err_msg = @silent_auction.errors.full_messages
        format.html { redirect_to silent_auction_path, :notice => err_msg }
        format.js { render 'fail_close_auction', :locals => { :errMsg => err_msg } }
      end
    end
  end

  def confirm_delete
    @title = "Confirm delete auction"
    @delete_auction = SilentAuction.find(params[:id])
    @bidders = User.joins(:bids).where(:bids => {:silent_auction_id => @delete_auction.id, :active => true}).order("username ASC")
    respond_to do |format|
      format.html
    end
  end

  # DELETE auction
  def destroy
    @auction = SilentAuction.find(params[:id])
    title = @auction.title
    @auction.destroy
    redirect_back_with_success(silent_auctions_path, "Item <strong>#{title}</strong> has been successfully deleted.".html_safe)
  end

  # Edit Auction
  # only allow edit running auction that has no bid
  def edit
    @title = "Edit Auction"
    @silent_auction = SilentAuction.find(params[:id])
    @silent_auction.photos.build if @silent_auction.photos.empty?
    unless @silent_auction.open
      redirect_back_with_error(silent_auctions_path,"You cannot edit closed auctions")
    else
      redirect_back_with_error(silent_auctions_path,"You cannot edit auctions that have active bids") if @silent_auction.has_active_bid
    end
  end

  # Update Auction
  def update
    @silent_auction = SilentAuction.find(params[:id])
    respond_to do |format|
      if @silent_auction.update_attributes(params[:silent_auction])
        format.html {
           flash[:success] = "<b>#{@silent_auction.title}</b> was successfully updated!".html_safe
            if @silent_auction.item_type == 'Silent Auction'
              redirect_to list_my_items_user_path(current_user)
            elsif @silent_auction.item_type == 'Normal Auction'
              redirect_to list_my_normal_auctions_user_path(current_user)
            else
              redirect_to list_my_sales_user_path(current_user)
            end
        }
      else
        format.html {
          @silent_auction.errors[:min_price].each do |msg|
            msg.insert(0, "Minimum price ")
          end
          @title = "Create New Auction"
          @silent_auction.photos.build if @silent_auction.photos.empty?
          render :action => 'edit'
        }
      end
    end
  end
end

app/helpers/silent_auctions_helper.rb
module SilentAuctionsHelper

  def user_bid_for_auction(auction)
    bid = current_user.bids.where(:silent_auction_id => auction.id).first
  end

  # return winner name
  def won_bid_for_auction(auction)
    winBid = auction.bids.active.highFirst.earlier.first
  end

  def formatted_date(date)
    date.to_s(:day_date_and_month)
  end

  def get_categories
    config_file = "#{Rails.root}/config/category.yml"
    categories = YAML.load_file(config_file)
  end
end

app/views/silent_auctions/_admin_sale_view.html.haml
%td.auction_controls
  .controls_holder
    %div{:class=>'btn-group manage_auction'}
      %button{:class => 'btn btn-mini btn-inverse dropdown-toggle', 'data-toggle' => 'dropdown'}
        %i{:class=>'icon-cog icon-white'}
        = "Manage"
        %span.caret
      %ul{:class => "dropdown-menu pull-right"}
        %li
          = link_to "<i class='icon-edit'></i> Edit Sale".html_safe, edit_silent_auction_path(auction)
        %li
          = link_to "<i class='icon-remove'></i> Delete".html_safe, confirm_delete_silent_auction_path(auction), :method => 'post'

app/views/silent_auctions/_category_search_filter.html.haml
= simple_form_for(:search, :method => "get") do |f|
  %table{:class => 'table table-simpleBordered'}
    %tbody
      %tr
        %td.auction_category{:width => "50"}
          %div{:class => 'form-horizontal'}
            = f.input :category, :as=>:select, :include_blank => "List All",:selected => category ,:collection => Category.all , :label_method => :category, :value_method => :id
        %td.auction_submit
          %div{:class => 'form-horizontal'}
            = submit_tag "Search", :name => "submit", :id => 'search_done', :class => 'btn btn-primary', :disable_with => "Search"

app/views/silent_auctions/_close_auction.html.haml
- wonBid = won_bid_for_auction(auction)
- if current_user.region == auction.region
  %tr{:class => 'auction', :id => "silentAuction_#{auction.id}"}
    %td.auction_photos
      = render :partial => 'silent_auctions/auction_photos', :locals => {:auction => auction}
    %td.auction_info
      %p.itemTitle= auction.title
      = simple_format(auction.description, :class => 'itemDescription')
      = simple_format("Winner: <span class='highlight'>#{wonBid.user.username}</span>", :class => 'itemWinner')
    -#%td.region
      -#= simple_format("Region:<br/><strong>#{auction.region.upcase}</strong>")
    %td.category
      = simple_format("Category:<br/><strong>#{(Category.find(auction.category_id)).category}</strong>")
    %td.min_price
      = simple_format("Min Price:<br/><strong>#{current_user.currency} #{number_with_delimiter(auction.min_price)}</strong>")
    %td.end_date
      = simple_format("End date:<br /><strong>#{formatted_date(auction.end_date)}</strong>")
    %td.auction_bids
      = simple_format("Winning Bid:<br/><span class='highlight'>#{current_user.currency} #{number_with_delimiter(wonBid.amount)}</span>")
    %td.auction_controls
      - if current_user.admin?
        .controls_holder
          = link_to "x".html_safe, confirm_delete_silent_auction_path(auction),
                                  :method => 'post',
                                  :class => "btn btn-mini delete_btn",
                                  :title => "delete_auction"
      - else
        = render :partial => "bids/user_bid_view", :locals => { :auction => auction, :wonBid => wonBid }

app/views/silent_auctions/_form.html.haml
%div{:class => 'well form-horizontal'}
  %legend Item Details
  = f.input :title, :label => 'Title', :input_html => {:class => "span6"}
  = f.input :category_id, :as=>:select, :include_blank => "Select a Category", :collection => Category.all, :label_method => :category, :value_method => :id
  - if @silent_auction.creator.nil?
    = f.input :creator, :as => :hidden, :input_html => {:value => current_user.username}
  - else
    = f.input :creator, :as => :hidden, :input_html => {:value => @silent_auction.creator}
  = f.input :item_type, :as => :radio_buttons, :collection => [['Silent Auction','Silent Auction'],['Normal Auction','Normal Auction'],['Quick Sale','Quick Sale']], :label_method => :last, :value_method => :first
  = f.input :min_price, :label => 'Minimum Price',:wrapper => :prepend do
    = content_tag :span, "#{current_user.currency}", :class => "add-on", :id => "silent_auction_currency"
    = f.input_field :min_price
  .text_counter
    = f.input :description, :as => :text, :label => 'Description', :input_html => { :rows => 8, :class => "span6", :id => "description" }
  = f.input :start_date, :label =>"Start date", :as => :string, :order =>[:day,:month,:year], :input_html => {:class =>"datePicker" }
  = f.input :end_date, :label =>"End date", :as => :string, :order =>[:day,:month,:year], :input_html => {:class =>"datePicker", :value => 2.weeks.from_now.in_time_zone(current_user.timezone).to_s(:date_month_and_year)}
%div{:class => 'well form-inline clearfix', :id => "image-upload"}
  %legend.file_upload
    = "Item Images"
    %span (maximum 6 uploads)
  %div{:style => 'margin-left:160px;'}
    = f.simple_fields_for :photos do |photo|
      = render :partial => "photos/photo_fields", :locals => {:f => photo}
    = f.link_to_add "<i class='icon-plus icon-white'></i> Add another image".html_safe, :photos, :class => "btn btn-success add-image-btn"

app/views/silent_auctions/_my_auction.html.haml
- bid = user_bid_for_auction(auction)
- if current_user.region == auction.region
  %tr{:class => "auction", :id => "silentAuction_#{auction.id}"}
    %td.auction_photos
      = render :partial => 'silent_auctions/auction_photos', :locals => {:auction => auction}
    %td.auction_info
      %p.itemTitle= auction.title
      = simple_format(auction.description, :class => 'itemDescription')
    %td.category
      = simple_format("Category:<br/><strong>#{(Category.find(auction.category_id)).category}</strong>")
    %td.min_price
      = simple_format("Min Price:<br/><strong>#{current_user.currency} #{number_with_delimiter(auction.min_price)}</strong>")
    %td.start_date
      = simple_format("Start date:<br /><strong>#{formatted_date(auction.start_date)}</strong>")
    %td.end_date
      = simple_format("End date:<br /><strong>#{formatted_date(auction.end_date)}</strong>")
    -#- if current_user.admin?
    = render :partial => "silent_auctions/admin_auction_view", :locals => { :auction => auction }

app/views/silent_auctions/_running_auction.html.haml
- bid = user_bid_for_auction(auction)
- if current_user.region == auction.region
  %tr{:class => "auction", :id => "silentAuction_#{auction.id}"}
    %td.auction_photos
      = render :partial => 'silent_auctions/auction_photos', :locals => {:auction => auction}
    %td.auction_info
      %p.itemTitle= link_to auction.title, new_silent_auction_auction_message_path(auction)
      = simple_format(auction.description, :class => 'itemDescription')
      = simple_format("Contact: <span class='highlight'>#{auction.creator}</span>", :class => 'itemWinner')
    %td.category
      = simple_format("Category:<br/><strong>#{(Category.find(auction.category_id)).category}</strong>")
    %td.min_price
      = simple_format("Min Price:<br/><strong>#{current_user.currency} #{number_with_delimiter(auction.min_price)}</strong>")
    %td.start_date
      = simple_format("Start date:<br /><strong>#{formatted_date(auction.start_date)}</strong>")
    %td.end_date
      = simple_format("End date:<br /><strong>#{formatted_date(auction.end_date)}</strong>")
    - if current_user.admin?
      = render :partial => "admin_auction_view", :locals => { :auction => auction }
    - else
      - if current_user.username != auction.creator
        = render :partial => "bids/user_bid_view", :locals => { :auction => auction, :bid => bid }
      - else
        -# %td
          -# &nbsp;
        %td.auction_bids
          - bid_count = auction.bids.active.count
          - if bid_count > 0
            %span{:class => 'badge badge-warning', :style => "font-weight:bold;"}
              = pluralize(bid_count, "bid")
          - else
            %span{:class => 'badge badge-error', :style => "font-weight:bold;"}
              = "0 bids"

app/views/silent_auctions/_running_normal_auction.html.haml
- bid = user_bid_for_auction(auction)
- if current_user.region == auction.region
  %tr{:class => "auction", :id => "silentAuction_#{auction.id}"}
    %td.auction_photos
      = render :partial => 'silent_auctions/auction_photos', :locals => {:auction => auction}
    %td.auction_info
      %p.itemTitle= link_to auction.title, new_silent_auction_auction_message_path(auction)
      = simple_format(auction.description, :class => 'itemDescription')
      = simple_format("Contact: <span class='highlight'>#{auction.creator}</span>", :class => 'itemWinner')
    %td.category
      = simple_format("Category:<br/><strong>#{(Category.find(auction.category_id)).category}</strong>")
    %td.min_price
      = simple_format("Min Price:<br/><strong>#{current_user.currency} #{number_with_delimiter(auction.min_price)}</strong>")
    %td.start_date
      = simple_format("Start date:<br /><strong>#{formatted_date(auction.start_date)}</strong>")
    %td.end_date
      = simple_format("End date:<br /><strong>#{formatted_date(auction.end_date)}</strong>")
    - if current_user.admin?
      = render :partial => "admin_normal_auction_view", :locals => { :auction => auction }
    - else
      - if current_user.username != auction.creator
        = render :partial => "bids/user_normal_bid_view", :locals => { :auction => auction, :bid => bid }
      - else
        -# %td
          -# &nbsp;
        %td.auction_bids
          - bid_count = auction.bids.active.count
          - if bid_count > 0
            %span{:class => 'badge badge-warning', :style => "font-weight:bold;"}
              -#= pluralize(bid_count, "bid")
              = "Highest Bid: #{current_user.currency} #{won_bid_for_auction(auction).amount}"
          - else
            %span{:class => 'badge badge-error', :style => "font-weight:bold;"}
              = "There's no bid yet"

app/views/silent_auctions/_running_sale.html.haml
- if current_user.region == auction.region
  %tr{:class => "auction", :id => "silentAuction_#{auction.id}"}
    %td.auction_photos
      = render :partial => 'silent_auctions/auction_photos', :locals => {:auction => auction}
    %td.auction_info
      %p.itemTitle= link_to auction.title, new_silent_auction_auction_message_path(auction)
      = simple_format(auction.description, :class => 'itemDescription')
      = simple_format("Contact: <span class='highlight'>#{auction.creator}</span>", :class => 'itemWinner')
    %td.category
      = simple_format("Category:<br/><strong>#{(Category.find(auction.category_id)).category}</strong>")
    %td.min_price
      = simple_format("Min Price:<br/><strong>#{current_user.currency} #{number_with_delimiter(auction.min_price)}</strong>")
    %td.start_date
      = simple_format("Start date:<br /><strong>#{formatted_date(auction.start_date)}</strong>")
    %td.end_date
      = simple_format("End date:<br /><strong>#{formatted_date(auction.end_date)}</strong>")
    - if current_user.admin?
      = render :partial => "admin_sale_view", :locals => { :auction => auction }

app/views/silent_auctions/close_auction.js.erb
$('.close_auction_btn').unbind('ajax:success');

$('.close_auction_btn').bind('ajax:success', function(){
    $("span.success").empty();
    var parent = $(this).closest('tr.auction');
    var pId = parent.attr('id');
    parent.fadeOut('slow', function() {
        parent.replaceWith(
                "<%= escape_javascript(render :partial => "close_auction", :locals => {:auction => @silent_auction}) %> "
        );
        $("#" + pId).addClass('just_closed').fadeIn();
    });
});

app/views/silent_auctions/edit.html.haml
%h1{:style => 'margin-bottom:20px;'} Edit Auction

= simple_nested_form_for @silent_auction, :html => { :multipart => true } do |f|
  = render :partial => 'form', :locals => {:f => f}

  %div{:class => 'form-horizontal'}
    %div{:class => 'form-actions'}
      - if @silent_auction.item_type == 'Silent Auction'
        = link_to "Back to Listing", silent_auctions_path, :class => 'btn'
      - else
        = link_to "Back to Listing", sales_silent_auctions_path, :class => 'btn'
      = submit_tag "Save changes", :class => 'btn btn-primary form_action_btn', :disable_with => "Saving changes..."

app/views/silent_auctions/expired.html.haml
- @user = current_user
%h1
  %span Expired Auctions
  - if current_user.admin?
    = link_to 'Create NEW Auction/Sale', new_silent_auction_path, :class => 'btn btn-success btn-large'

- if @expired_auctions.blank?
  %h3= "No auctions found"
  .empty_collection
    %p.emptyMsg There are no expired auctions.
- else
  - status = page_entries_info @expired_auctions
  - replacements = [ ["silent", "expired"], ["entries", "auctions"] ]
  - replacements.each {|replacement| status.gsub!(replacement[0], replacement[1])}
  %h3= status.html_safe
  %table{:class => 'table table-simpleBordered', :id => 'expiredAuctions'}
    %tbody
      - @expired_auctions.each do |auction|
        = render :partial => "expired_auction", :locals => { :auction => auction }
  %div{:class => 'index_footer clearfix'}
    = paginate @expired_auctions
    .pagination_info
      = (page_entries_info @expired_auctions).sub("silent", "expired").html_safe

app/views/silent_auctions/fail_close_auction.js.erb
$('.close_auction_btn').unbind('ajax:success');
$('.close_auction_btn').bind('ajax:success', function(){
    var parent = $(this).parent();
    parent.find(".msg").remove();
    parent.append("<div class='error msg'><%= errMsg %></div>");
    $("span.success").empty();
});

app/views/silent_auctions/new.html.haml
%h1{:style => 'margin-bottom:20px;'} Create New Item

= simple_nested_form_for @silent_auction, :html => { :multipart => true } do |f|
  = render :partial => 'form', :locals => {:f => f}

  %div{:class => 'form-horizontal'}
    %div{:class => 'form-actions'}
      = link_to "Back to Listing", silent_auctions_path, :class => 'btn'
      -#= submit_tag "Save and create another auction", :name => "continue", :id => 'submit_continue', :class => 'btn btn-primary form_action_btn', :disable_with => "Save and create another auction"
      -#= submit_tag "Save and go back to listing", :name => "done", :id => 'submit_done', :class => 'btn btn-primary form_action_btn', :disable_with => "Save and go back to listing"
      = submit_tag "Save and go back to listing", :name => "done", :id => 'submit_done', :class => 'btn btn-primary form_action_btn', :disable_with => "Save and go back to listing"
      = submit_tag "Save and create another auction", :name => "continue", :id => 'submit_continue', :class => 'btn btn-primary form_action_btn', :disable_with => "Save and create another auction"

app/views/silent_auctions/normal_auctions.html.haml
- @user = current_user
%h1
  %span Running Auctions
  -#- if current_user.admin?
  = link_to new_silent_auction_path, {:class => 'btn btn-success btn-large'} do
    %i{:class => 'icon-white icon-plus-sign'}
      %span
        Create New Auction
  = render :partial => "category_search_filter", :locals => { :category => @search_category }
  %hr
- if @running_auctions.blank?
  %h3= "No auctions found"
  .empty_collection
    %p.emptyMsg There are no running auctions.
- else
  %h3= "Displaying all #{pluralize(@running_auctions.count, "running auctions")}"
  %table{:class => 'table table-simpleBordered', :id => 'runningAuctions'}
    %tbody
      - @running_auctions.each do |auction|
        = render :partial => "running_normal_auction", :locals => { :auction => auction }