config/routes.rb
TWAmazon::Application.routes.draw do
  resources :email_notifications
  resources :categories

  match '/landing',    to: 'home#landing'

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :silent_auctions do
    member do
      put 'close'
      post 'confirm_delete'
    end

    collection do
      get 'closed'
      get 'expired'
      get 'future'
      get 'normal_auctions'
      get 'sales'
    end
    resources :auction_messages
    resources :photos, :only => [:index, :create, :destroy]
  end

  resources :bids, :only => [:create, :new, :update] do
    member do
      put 'withdraw'
      post 'update_amount'
      put 'delete'
    end
  end

  resources :faqs, :only  => [:index]

  resources :users, :only => [:show] do
    member do
      get :notification
      get :list_my_items
      get :list_my_normal_auctions
      get :list_my_sales
      get :new_region
      post :update_region
    end
  end

  root :to => 'home#login'
  devise_for :users, :skip => [:sessions], :controllers => { :omniauth_callbacks => "sessions"}
  devise_scope :user do
    get '/login', :to => "sessions#new", :as => :new_user_session
  end

  #Routes to dummy session controller for dev and test environments
  unless Rails.env.production?
    devise_for :users,
      :controllers => { :sessions => "dummy_sessions" },
      :path_names => { :sign_in => '/test_users/login', :sign_out => 'test-users/logout'},
      :except => [:new_user_session, :destroy_user_session]

    devise_scope :user do
      get '/test-users/login', :to => 'dummy_sessions#new', :as => :new_user_session
      get '/test-users/logout', :to => 'dummy_sessions#destroy', :as => :destroy_user_session
    end
  end
end

app/models/bid.rb
class Bid < ActiveRecord::Base
  belongs_to :silent_auction, :inverse_of => :bids
  belongs_to :user, :inverse_of => :bids

  validates :amount, :presence => { :message => "is required" }, :numericality => true #, :numericality => {:less_than_or_equal_to => 9999.99}
  validates :amount, :format => { :with => /^\d+(\.\d{0,2})?$/, :message => "can only have 2 decimal places" }
  validates :silent_auction_id, :presence => true, :uniqueness => {:scope => :user_id, :message => 'You cannot place multiple bids for an auction.'}
  validate :validate_bid_limit
  validate :amount_must_be_greater_than_auction_min_price
  validate :auction_must_not_be_closed

  attr_accessible :amount, :active, :silent_auction_id, :created_at, :as => [:default, :admin]
  attr_accessible :user_id, :as => :admin

  scope :active, where(:active => true)
  scope :highFirst, order('amount DESC')
  scope :earlier, order('created_at ASC')
  scope :recent, order('"silent_auctions"."created_at" desc')

  def validate_bid_limit
    return unless amount
    item = SilentAuction.find(silent_auction_id)
    maximum = item.region.maximum.to_f
    currency = item.region.currency
    valid = self.amount < maximum
    unless valid
      warning = number_with_delimiter(maximum, :delimiter => ",").to_s
      errors.add(:amount, " can't exceed #{currency} #{warning}")
    end
    return valid
  end

  def number_with_delimiter(number, options = {})
    options.symbolize_keys!

    begin
      Float(number)
    rescue ArgumentError, TypeError
      if options[:raise]
        raise InvalidNumberError, number
      else
        return number
      end
    end
  end

  def auction_must_not_be_closed
    # not allow placing bid for closed auction
    errors.add :silent_auction_id, "cannot be placed for closed auction" unless SilentAuction.find(self.silent_auction_id).open
  end

  def amount_must_be_greater_than_auction_min_price
    if self.amount != nil
      #errors.add :amount, "cannot be less than minimum price" unless SilentAuction.find(self.silent_auction_id).min_price <= self.amount
      auction = SilentAuction.find(self.silent_auction_id)
      if auction.item_type == 'Silent Auction'
        errors.add :amount, "cannot be less than minimum price" unless auction.min_price <= self.amount
      else
        highestBid = auction.bids.active.highFirst.earlier.first
        if highestBid.nil?
          errors.add :amount, "cannot be less than minimum price" unless auction.min_price <= self.amount
        else
          errors.add :amount, "must be higher than the current highest bid" unless highestBid.amount < self.amount
        end
      end
    end
  end

  def withdraw
    if SilentAuction.find(self.silent_auction_id).open
      self.turn_inactive
      true
    else
      errors.add :base, "Auction has been closed! Bid cannot be withdrawn anymore."
      false
    end
  end

  def turn_inactive
    self.active = false
    self.save!
  end

end

app/controllers/bids_controller.rb
class BidsController < ApplicationController
  include ApplicationHelper
  before_filter :authenticate_user!

  def create
    @bid = current_user.bids.build(params[:bid])
    @auction = SilentAuction.find(@bid.silent_auction_id)
    respond_to do |format|
      if @bid.save
        send_outbid_email @auction if @auction.bids.size > 1 and @auction.item_type != 'Silent Auction'
        send_item_will_sell_email @auction if @auction.bids.size == 1
        if @auction.item_type == 'Silent Auction'
          format.html { redirect_back_with_success(silent_auctions_path,"") }
          format.js { render 'create'}
        else
          format.html { redirect_back_with_success(normal_auctions_silent_auctions_path,"") }
          format.js { render 'update'}
        end
      else
        err_msg = @bid.errors.full_messages[0]
        if @auction.item_type == 'Silent Auction'
          format.html { redirect_back_with_error(silent_auctions_path,"Error! #{err_msg}") }
        else
          format.html { redirect_back_with_error(normal_auctions_silent_auctions_path,"Error! #{err_msg}") }
        end
        format.js { render 'fail', :locals => { :errMsg => "#{err_msg}" } }
      end
    end
  end

  def update
    lastBid = Bid.where("silent_auction_id = ? AND user_id = ?", params[:bid]['silent_auction_id'], current_user.id).first
    @bid = lastBid
    @bid.amount = params[:bid]['amount']
    respond_to do |format|
      if @bid.save
        @auction = SilentAuction.find(@bid.silent_auction_id)
        send_outbid_email @auction if @auction.bids.size > 1 and @auction.item_type != 'Silent Auction' and current_user.id!=@auction.bids.last(2)[0].user_id
        format.html { redirect_back_with_success(normal_auctions_silent_auctions_path,"") }
        format.js { render 'update'}
      else
        err_msg = @bid.errors.full_messages[0]
        format.html { redirect_back_with_error(normal_auctions_silent_auctions_path,"") }
        format.js { render 'fail', :locals => { :errMsg => "#{err_msg}" } }
      end
    end
  end

  def withdraw
    @bid = Bid.find(params[:id])
    if @bid.user_id != current_user.id
      session[:return_to] ||= request.referer
      flash[:error] = "<h4 class='alert-heading'>Unauthorized Withdrawal!</h4>You cannot withdraw bids of other users"
      redirect_back_or silent_auctions_path
    else
      @auction = SilentAuction.find(@bid.silent_auction_id)
      respond_to do |format|
        if @bid.withdraw
            @bids_email =  Bid.where("silent_auction_id = ?",@bid.silent_auction_id)
            if @bids_email.size>0
              @user_id = @bids_email.last.user_id
              if current_user.id!=@user_id
                @outBidder_id = User.find(@user_id).username
                UserMailer.item_withdraw(@auction.title,@outBidder_id).deliver
              end
            end
            msg = "Bid withdrawn successfully"
            format.html { redirect_back_with_success(silent_auctions_path, msg) }
            format.js { render 'withdraw_done' }
        else
          err_msg = @bid.errors.full_messages[0]
          format.html { redirect_back_with_error(silent_auctions_path,"Error! #{err_msg}") }
          format.js { render 'fail_withdraw', :locals => { :errMsg => err_msg } }
        end
      end
    end
  end

  def update_amount
    puts "*" * 20

    last_bid = Bid.where("user_id = ? AND silent_auction_id = ?", params)

    currentHighestBid = SilentAuction.find(@bid.silent_auction_id).bids.active.highFirst.earlier.first
    puts currentHighestBid

    respond_to do |format|
      flash[:error] = "Test"
      format.html { redirect_back_with_success(silent_auctions_path, "msg") }
    end
  end

  def delete
    @bid = Bid.find(params[:id])
    silent_auction_id = @bid.silent_auction_id
    puts "*" * 20
    @auction = SilentAuction.find(silent_auction_id)
    puts @auction.bids.active.count
    @bid.destroy
    puts @auction.title
    puts @auction.bids.active.count
    @bids_email =  Bid.where("silent_auction_id = ?",@bid.silent_auction_id)
    if @bids_email.size>0
      @user_id = @bids_email.last.user_id
      if current_user.id!=@user_id
        @outBidder_id = User.find(@user_id).username
        UserMailer.item_withdraw(@auction.title,@outBidder_id).deliver
      end
    end
    respond_to do |format|
      msg = "Bid withdrawn successfully"
      format.html { redirect_back_with_success(normal_auctions_silent_auctions_path, msg) }
      format.js { render 'delete_done' }
    end
  end

  private
  def send_outbid_email auction
     bids = auction.bids.last(2)
     outBidder = User.find(bids[0].user_id).username
     UserMailer.item_outbid(auction.title, outBidder).deliver
  end

  def send_item_will_sell_email auction
    user = User.find_by_username auction.creator
    email_notification = EmailNotification.find_by_users_id user.id
    UserMailer.item_will_sell(auction.title, auction.creator).deliver if email_notification and email_notification.item_will_sell
  end

end

app/views/bids/_newBidForm.html.haml
= simple_form_for (Bid.new), :remote => true, :html => { :class => 'form-inline bid_form' } do |f|
  -#= f.input :amount, :label => "Your Bid", :input_html => {:class => "span1", :type => "text"}
  = f.input :amount, :label => "Your Bid", :wrapper => :prepend do
    = content_tag :span, "#{current_user.currency}", :class => "add-on", :id => "bid_amount_currency"
    = f.input_field :amount, :class => 'span1'
  = f.hidden_field :silent_auction_id, :value => auction.id
  = submit_tag "Place Bid", :class => 'btn btn-primary btn-mini', :disable_with => "Submitting..."

app/views/bids/_newNormalBidForm.html.haml
= simple_form_for (Bid.new), :remote => true, :html => { :class => 'form-inline bid_form' } do |f|
  -#- @bid = Bid.new
  -#= simple_form_for @bid, :remote => true, :html => { :class => 'form-inline bid_form' } do |f|
  -#= f.input :amount, :label => "Your Bid", :input_html => {:class => "span1", :type => "text"}
  - bid_count = @auction.bids.active.count
  - if bid_count > 0
    %span{:class => 'badge badge-warning', :style => "font-weight:bold;"}
      = "Highest Bid: #{current_user.currency} #{won_bid_for_auction(auction).amount}"
  - else
    %span{:class => 'badge badge-error', :style => "font-weight:bold;"}
      = "There's no bid yet !"
  %br
  %br
  = f.input :amount, :label => "Your Bid", :wrapper => :prepend do
    = content_tag :span, "#{current_user.currency}", :class => "add-on", :id => "bid_amount_currency"
    = f.input_field :amount, :class => 'span1'
  = f.hidden_field :silent_auction_id, :value => auction.id
  = submit_tag "Place Bid", :class => 'btn btn-primary btn-mini', :disable_with => "Submitting..."

app/views/bids/_updateNormalBidForm.html.haml
-#= simple_form_for bid, :remote => true, :url => { :action => update_amount_bid_path(bid), :controller => bid }, :html => { :class => 'form-inline bid_form', :multipart => false, :method => :post } do |f|
= simple_form_for bid, :remote => true, :html => { :class => 'form-inline bid_form'} do |f|
  - bid.amount = ""
  - auction = SilentAuction.find(bid.silent_auction_id)
  %span{:class => 'badge badge-warning', :style => "font-weight:bold;"}
    = "Highest Bid: #{current_user.currency} #{won_bid_for_auction(auction).amount}"
  %br
  %br
  = f.input :amount, :label => "Your Last Bid: #{current_user.currency} #{user_bid_for_auction(auction).amount}", :wrapper => :prepend do
    = content_tag :span, "#{current_user.currency}", :class => "add-on", :id => "bid_amount_currency"
    = f.input_field :amount, :class => 'span1'
  = f.hidden_field :silent_auction_id, :value => auction.id
  = submit_tag "Update Bid", :class => 'btn btn-primary btn-mini', :disable_with => "Updating..."

  = link_to "Withdraw Bid", delete_bid_path(bid),
        :method => 'put',
        :confirm => "Are you sure. Continue?",
        :class => "btn btn-danger btn-mini withdraw_bid",
        :remote => true,
        :disable_with => "Withdrawing..."

app/views/bids/_user_bid_view.html.haml
- bid = user_bid_for_auction(auction)
- if auction.open?
  %td{ :id => "bid_for_auction_#{auction.id}", :class =>"bid_col", :html => "colspan='2'"}
    - if bid != nil
      - if bid.active?
        = render :partial => "bids/withdrawBidForm", :locals => { :bid => bid }
      - else
        = render :partial => "bids/withdrawnBid", :locals => { :bid => bid }
    - else
      = render :partial => "bids/newBidForm", :locals => { :auction => auction }
- else
  - if bid != nil
    - if bid.active
      - if bid.id == wonBid.id
        -#= simple_format("Your Bid:<br/><span class='highlight'>#{number_to_currency(bid.amount)}</span>")
        = simple_format("Your Bid:<br/><span class='highlight'>#{auction.currency} #{number_with_delimiter(bid.amount)}</span>")
      - else
        -#= simple_format("Your Bid:<br/><span class='lost'>#{number_to_currency(bid.amount)}</span>")
        = simple_format("Your Bid:<br/><span class='lost'>#{auction.currency} #{number_with_delimiter(bid.amount)}</span>")
    - else
      = simple_format("Your Bid: <span class='delBid'>#{auction.currency} #{number_with_delimiter(bid.amount)}</span>")
      %span{:style => 'font-weight:bold; color:#f00'} WITHDRAWN
  - else
    &nbsp;

app/views/bids/_user_normal_bid_view.html.haml
- bid = user_bid_for_auction(auction)
- bid_count = auction.bids.active.count
- if auction.open?
  %td{ :id => "bid_for_auction_#{auction.id}", :class =>"bid_col", :html => "colspan='2'"}
    - if bid != nil
      = render :partial => "bids/updateNormalBidForm", :locals => { :auction => auction, :bid => bid }
    - else
      - @auction = auction
      = render :partial => "bids/newNormalBidForm", :locals => { :auction => @auction }
- else
  - if bid != nil
    - if bid.active
      - if bid.id == wonBid.id
        -#= simple_format("Your Bid:<br/><span class='highlight'>#{number_to_currency(bid.amount)}</span>")
        = simple_format("Your Bid:<br/><span class='highlight'>#{auction.currency} #{number_with_delimiter(bid.amount)}</span>")
      - else
        -#= simple_format("Your Bid:<br/><span class='lost'>#{number_to_currency(bid.amount)}</span>")
        = simple_format("Your Bid:<br/><span class='lost'>#{auction.currency} #{number_with_delimiter(bid.amount)}</span>")
  - else
    &nbsp;

app/views/bids/_withdrawBidForm.html.haml
-#= simple_format("Your bid: <b>#{number_to_currency(bid.amount)}</b><span class='success'></span>")
= simple_format("Your bid: <b>#{current_user.currency} #{number_with_delimiter(bid.amount)}</b><span class='success'></span>")
= link_to "Withdraw Bid", withdraw_bid_path(bid),
      :method => 'put',
      :confirm => "You won't be able to bid on this auction again after withdrawing. Continue?",
      :class => "btn btn-danger btn-mini withdraw_bid",
      :remote => true,
      :disable_with => "Submitting..."

app/views/bids/_withdrawnBid.html.haml
-#= simple_format("Your bid: <span class='delBid'>#{number_to_currency(bid.amount)}</span>")
= simple_format("Your bid: <span class='delBid'>#{current_user.currency} #{number_with_delimiter(bid.amount)}</span>")
%span{:style => 'font-weight:bold; color:#f00'} WITHDRAWN

app/views/bids/create.js.erb
$('.bid_form').unbind('ajax:success');
$('.bid_form').bind('ajax:success', function(){
    var parent = $(this).parent();
    $(this).fadeOut().remove();
    parent.append(
            "<%= escape_javascript(render :partial => "bids/withdrawBidForm", :locals => {:bid => @bid}) %> "
    ).fadeIn();
    $("span.success").empty();
    parent.find("span.success").append("<i class='icon-ok icon-green'></i>");
});

app/views/bids/delete_done.js copy.erb
$('.withdraw_bid').unbind('ajax:success');
$('.withdraw_bid').bind('ajax:success', function(){
    var parent = $(this).parent();
    parent.empty();
    parent.append(
            "<%= escape_javascript(render :partial => "bids/newNormalBidForm", :locals => {:auction => @auction}) %> "
    ).fadeIn();
    $("span.success").empty();
});

app/views/bids/delete_done.js.erb
$('.bid_form').unbind('ajax:success');
$('.bid_form').bind('ajax:success', function(){
    var parent = $(this).parent();
    $(this).fadeOut().remove();
    parent.append(
            "<%= escape_javascript(render :partial => "bids/newNormalBidForm", :locals => {:auction => @auction}) %> "
    ).fadeIn();
    $("span.success").empty();
    parent.find("span.success").append("<i class='icon-ok icon-green'></i>");
});

app/views/bids/fail.js.erb
$('.bid_form').unbind('ajax:success');
$('.bid_form').bind('ajax:success', function(){
    $(this).find(".msg").remove();
    $(this).append("<div class='error msg'><%= errMsg %></div>");
});

app/views/bids/fail_withdraw.js.erb
$('.withdraw_bid').unbind('ajax:success');
$('.withdraw_bid').bind('ajax:success', function(){
    var parent = $(this).parent();
    parent.find(".msg").remove();
    parent.append("<div class='error msg'><%= errMsg %></div>");
    $("span.success").empty();
});

app/views/bids/update.js.erb
$('.bid_form').unbind('ajax:success');
$('.bid_form').bind('ajax:success', function(){
    var parent = $(this).parent();
    $(this).fadeOut().remove();
    parent.append(
            "<%= escape_javascript(render :partial => "bids/updateNormalBidForm", :locals => {:bid => @bid}) %> "
    ).fadeIn();
    $("span.success").empty();
    parent.find("span.success").append("<i class='icon-ok icon-green'></i>");
});

app/views/bids/withdraw_done.js.erb
$('.withdraw_bid').unbind('ajax:success');
$('.withdraw_bid').bind('ajax:success', function(){
    var parent = $(this).parent();
    parent.empty();
    parent.append(
            "<%= escape_javascript(render :partial => "bids/withdrawnBid", :locals => {:bid => @bid}) %> "
    ).fadeIn();
    $("span.success").empty();
});