config/routes.rb
TWAmazon::Application.routes.draw do
  resources :email_notifications
  resources :categories

  match '/landing',    to: 'home#landing'

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :silent_auctions do
    member do
      put 'close'
      post 'confirm_delete'
    end

    collection do
      get 'closed'
      get 'expired'
      get 'future'
      get 'normal_auctions'
      get 'sales'
    end
    resources :auction_messages
    resources :photos, :only => [:index, :create, :destroy]
  end

  resources :bids, :only => [:create, :new, :update] do
    member do
      put 'withdraw'
      post 'update_amount'
      put 'delete'
    end
  end

  resources :faqs, :only  => [:index]

  resources :users, :only => [:show] do
    member do
      get :notification
      get :list_my_items
      get :list_my_normal_auctions
      get :list_my_sales
      get :new_region
      post :update_region
    end
  end

  root :to => 'home#login'
  devise_for :users, :skip => [:sessions], :controllers => { :omniauth_callbacks => "sessions"}
  devise_scope :user do
    get '/login', :to => "sessions#new", :as => :new_user_session
  end

  #Routes to dummy session controller for dev and test environments
  unless Rails.env.production?
    devise_for :users,
      :controllers => { :sessions => "dummy_sessions" },
      :path_names => { :sign_in => '/test_users/login', :sign_out => 'test-users/logout'},
      :except => [:new_user_session, :destroy_user_session]

    devise_scope :user do
      get '/test-users/login', :to => 'dummy_sessions#new', :as => :new_user_session
      get '/test-users/logout', :to => 'dummy_sessions#destroy', :as => :destroy_user_session
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  include ApplicationHelper
  before_filter :authenticate_user!, :only => :landing
  before_filter :ensure_signed_in_user_has_a_region, :only => :landing
  def login
    if user_signed_in?
      redirect_to landing_path
    else
      unless Rails.env.production?
        redirect_to new_user_session_path
      else
        redirect_to user_omniauth_authorize_path(:saml)
      end
    end
  end

  def landing
    @title = "Running Silent Auctions"
    @search_category=""
    @running_auctions = SilentAuction.running(current_user.timezone).recent.includes(:bids).where("region_id = '#{current_user.region_id}'")
    temp = SilentAuction.running(current_user.timezone).recent.includes(:bids).where("region_id = '#{current_user.region_id}'")
    temp.each do |auction|
      if auction.end_date < Date.today
        temp.delete(auction)
      end
    end
    @ending_soon = temp.sort! {|a,b| a.end_date <=> b.end_date}
  end

end

app/helpers/home_helper.rb
module HomeHelper
  def days_left(ending_soon)
    #if ending_soon.end_date < Time.now.to_date # ended already
    #  return 'Ended'
    #elsif ending_soon.end_date > (Time.now.to_date + 1.day) # more than 1 day away
    #  diff_in_days = ((ending_soon.end_date - Time.now.to_date).to_i / 1.day)
    #  days_string = diff_in_days.to_s
    #  days_string += (diff_in_days > 1) ? ' Days' : ' Day'
    #  return days_string
    #else # ending today
    #  diff_in_HMS = Time.at(ending_soon.end_date - Time.now.to_date).gmtime.strftime('%R:%S')
    #  return diff_in_HMS
    #end
    if ending_soon.end_date < Date.today
      return 'Ended'
    elsif ending_soon.end_date == Date.today
      return 'Ending Today'
    else
      return ((ending_soon.end_date - Date.today).to_i)

    end
  end
end

app/views/home/_auction_photos.html.haml
- photos = auction.photos
- if photos.empty?
  %div{:class=>'photo_area'}
    = image_tag(asset_path("img_placeholder.jpg"))
- else
  - if photos.count == 1
    %div{:class=>'photo_area'}
      %a{:class => 'gallery', :rel => "photos_auction_#{auction.id}", :href => photos[0].image_url.to_s, :title => photos[0].caption}
        = image_tag photos[0].image_url(:thumb).to_s
  - else
    %div{:class=>'albums'}
      %a{:class => 'gallery', :rel => "photos_auction_#{auction.id}", :href => photos[0].image_url.to_s, :title => photos[0].caption}
        = image_tag photos[0].image_url(:thumb).to_s
    %div{:style=>"visibility:hidden"}
      - photos.each_with_index do |photo, index|
        - unless index == 0
          = link_to "", photo.image_url.to_s, :class => "gallery", :rel => "photos_auction_#{auction.id}", :title => photo.caption

app/views/home/_ending_soon.html.haml
%li{:class => "span4", :id => "silentAuction_#{@ending_soon.id}"}
  %div{:class => "thumbnail"}
    = render :partial => 'auction_photos', :locals => {:auction => @ending_soon}
    %br
    %span.well "AU$ #{@ending_soon.min_price}"
    %hr
    %div
      = link_to new_silent_auction_auction_message_path(@ending_soon) , {:class => 'btn btn-large'}  do
        %i{:class => 'icon-info-sign'}
        -if @ending_soon.title.length < 23
          #{@ending_soon.title}
        -else
          #{(@ending_soon.title)[0..23] + "...."}
    %hr
    -if days_left(@ending_soon) == 'Ending Today'
      %span{:class => 'label label-important'} Time Left:Today
    -else
      %span{:class => 'label label-success'} Time Left: #{days_left(@ending_soon)} days

app/views/home/_most_recent.html.haml
%li{:class => "span4", :id => "silentAuction_#{@running_auction.id}"}
  %div{:class => "thumbnail"}
    = render :partial => 'auction_photos', :locals => {:auction => @running_auction}
    %br
    %span.well "AU$ #{@running_auction.min_price}"
    %hr
    %div
      = link_to new_silent_auction_auction_message_path(@running_auction) , {:class => 'btn btn-large'}  do
        %i{:class => 'icon-info-sign'}
        -if @running_auction.title.length < 25
          #{@running_auction.title}
        -else
          #{(@running_auction.title)[0..25] + "...."}

app/views/home/landing.html.haml
- @user = current_user
%div.page-header
  %h1
    Welcome
    %small
      #{@user.username}
  = link_to new_silent_auction_path, {:class => 'btn btn-success btn-large'} do
    -#%span{:class => 'ui-icon ui-icon-circle-plus'}
    Create New Auction

%h1 Most Recent
-if @running_auctions.blank?
  %h4.well No Recent Auctions
-else
  %ul{:class=> 'thumbnails', :id => 'mostRecentAuctions'}
    - @running_auctions[0..4].each do |auction|
      = render :partial => "most_recent", :locals => { :@running_auction => auction }

%hr
%h1 Ending Soon
-if @ending_soon.blank?
  %h4.well No Recent Auctions
-else
  %ul.thumbnails
    - @ending_soon[0..4].each do |auction|
      = render :partial => "ending_soon", :locals => { :@ending_soon => auction }