config/routes.rb
TWAmazon::Application.routes.draw do
  resources :email_notifications
  resources :categories

  match '/landing',    to: 'home#landing'

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :silent_auctions do
    member do
      put 'close'
      post 'confirm_delete'
    end

    collection do
      get 'closed'
      get 'expired'
      get 'future'
      get 'normal_auctions'
      get 'sales'
    end
    resources :auction_messages
    resources :photos, :only => [:index, :create, :destroy]
  end

  resources :bids, :only => [:create, :new, :update] do
    member do
      put 'withdraw'
      post 'update_amount'
      put 'delete'
    end
  end

  resources :faqs, :only  => [:index]

  resources :users, :only => [:show] do
    member do
      get :notification
      get :list_my_items
      get :list_my_normal_auctions
      get :list_my_sales
      get :new_region
      post :update_region
    end
  end

  root :to => 'home#login'
  devise_for :users, :skip => [:sessions], :controllers => { :omniauth_callbacks => "sessions"}
  devise_scope :user do
    get '/login', :to => "sessions#new", :as => :new_user_session
  end

  #Routes to dummy session controller for dev and test environments
  unless Rails.env.production?
    devise_for :users,
      :controllers => { :sessions => "dummy_sessions" },
      :path_names => { :sign_in => '/test_users/login', :sign_out => 'test-users/logout'},
      :except => [:new_user_session, :destroy_user_session]

    devise_scope :user do
      get '/test-users/login', :to => 'dummy_sessions#new', :as => :new_user_session
      get '/test-users/logout', :to => 'dummy_sessions#destroy', :as => :destroy_user_session
    end
  end
end

app/views/layouts/_site_navigation.html.haml
%ul.nav
  %li{:class => 'divider-vertical divider-left'}
  -#- unless current_user.region.nil?
  - unless current_user.region.nil?
    - unless current_user.region == ""
      -#%li
        -#= link_to "Quick Sales Board", sales_silent_auctions_path, :class => is_active?('sales')
      -#%li
        -#= link_to "Running Auctions", silent_auctions_path, :class => is_active?('index')
      %li.dropdown
        -#%a{:href => "#", :id => 'user_menu', :class => "dropdown-toggle", "data-toggle" => "dropdown"}
        %a{:href => "#", :id => 'deals_menu', :class => "#{is_active?('sales')} #{is_active?('index')}", "data-toggle" => "dropdown"}
          = 'Current Deals'
          -#%span
            -#Current Deals
            -#%b.caret
        %ul{:class => "dropdown-menu", :role => 'menu'}
          -#- if not(current_user.admin?)
          %li=link_to("Silent Auctions", silent_auctions_path)
          %li=link_to("Normal Auctions", normal_auctions_silent_auctions_path)
          %li=link_to("Quick Sales", sales_silent_auctions_path)
      %li.dropdown
        = link_to "Closed Auctions", closed_silent_auctions_path, :class => is_active?('closed')
      - if current_user.admin?
        %li.dropdown
          = link_to "Expired Auctions", expired_silent_auctions_path, :class => is_active?('expired')

app/views/layouts/_user_menu.html.haml
%ul{:class => "nav pull-right"}
  - unless current_user.region.blank?
    %li{:id => "region-selector", :class => ""}
      %span{:id => "countryselect"}
        = simple_nested_form_for current_user, :html => { :multipart => false } do |f|
          = f.collection_select :region, get_regions,"code", "code", :selected => current_user.region.code, :onchange => 'alert(@user);'
  %li.divider-vertical
  %li.dropdown
    %a{:href => "#", :id => 'user_menu', :class => "dropdown-toggle", "data-toggle" => "dropdown"}
      %span{:class=>"label label-inverse loginStatus"}
        %i{:class => "icon-user icon-white"}
        Logged in as:
        %span{:style => "color:#FFD406"}
          = current_user.username
        - if current_user.admin?
          %span{:class => "loginStatus"} [ ADMIN ]
        %b.caret
    %ul{:class => "dropdown-menu"}
      %li=link_to "My Bids", user_path(current_user) unless current_user.admin?
      %li=link_to "Admin Dashboard", '/admin' if current_user.admin?
      %li=link_to "My Silent Auctions", list_my_items_user_path(current_user)
      %li=link_to "My Normal Auctions", list_my_normal_auctions_user_path(current_user)
      %li=link_to "My Sales", list_my_sales_user_path(current_user)
      %li=link_to "Email Notification Setting",new_email_notification_path
      %li=link_to "Frequently Asked Questions", faqs_path

app/views/layouts/application.html.haml
!!! 5
%html
%head
  %title
    = "Garage Sale | #{@title}"
  = favicon_link_tag '/assets/favicon_b.png'
  = stylesheet_link_tag    "application", :media => "all"
  = javascript_include_tag "application"
  = csrf_meta_tags

%body
  %div{:id => 'submit-overlay'}
  %div{:class => 'navbar navbar-fixed-top'}
    .navbar-inner
      .container
        - if user_signed_in?
          // btn-navbar is used as the toggle for collapsed navbar content
          %a{ :class =>"btn btn-navbar", 'data-toggle' => 'collapse', 'data-target' => '.nav-collapse'}
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar

          %a(title='Home'){:href => "/", :class => 'brand'} Garage Sale

          .nav-collapse
            = render :partial => 'layouts/site_navigation'
            = render :partial => 'layouts/user_menu'
        - else
          %a{:class => "brand"} &nbsp;
  .container
    - flash.each do |name, msg|
      %div{:class => "alert alert-#{ (name == :success || name == :notice) ? 'success' : 'error' }"}
        %a.close{"data-dismiss" => "alert"} x
        = msg
    = yield

app/views/layouts/show_errors.html.haml
%div{:class => 'alert alert-block confirm_delete'}
  %h2= @error_heading
  %p{:class => "warningText"}= @error_msg
%div.btn_wrapper
  =link_to "Back", back_link(index_path), :class => "btn"
  =link_to "Go to home page", index_path, :class => "btn"